server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active:
      - "prod"
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"


cards:
  message: "Welcome to Bank loan related api"
  contactDetails:
    name: "sundar"
    email: "sundar@gmail.com"
  onCallSupport:
    - "(91)9472429747"
    - "(91)9274238293"