spring:
  config:
    activate:
      on-profile: "qa"


loans:
  message: "Welcome to Bank card related api qa"
  contactDetails:
    name: "sundar"
    email: "sundar@gmail.com"
  onCallSupport:
    -(91)9472429747
    -(91)9274238293